org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/ComposedStructureInnerSwitch.java
Case for RequiredInfrastructureDelegationConnectors has been missing.
=> Support RequiredInfrastructureDelegationConnector

org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/runtimestate/SimulatedBasicComponentInstance.java
Enables one to receive the available instances of a passive resource.
Jira: [SIMULIZAR-91](https://sdqbuild.ipd.kit.edu/jira/browse/SIMULIZAR-91)
=> Add getAvailablePassiveResource method to SimulatedBasicComponentInstance

bundles/org.palladiosimulator.simulizar.action/src-man/org/palladiosimulator/simulizar/action/interpreter/ActionProfileProvider.java, bundles/org.palladiosimulator.simulizar.action/src-man/org/palladiosimulator/simulizar/action/interpreter/TransientEffectExecutionResult.java
There is at least one unused import that causes compilation problems for me. Therefore, I removed it (and another one that does not cause any problems).
=> Removed unused imports.

bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java
see https://jira.palladio-simulator.com/projects/SIMULIZAR/issues/SIMULIZAR-112
=> [SIMULIZAR-112] Prevent superflous observer registration

bundles/org.palladiosimulator.simulizar.aggregation/src/org/palladiosimulizar/aggregation/probeframework/AggregatorsProbeFrameworkListenerDecorator.java, bundles/org.palladiosimulator.simulizar.elasticity/src/org/palladiosimulator/simulizar/elasticity/jobs/RunElasticityAnalysisJob.java, bundles/org.palladiosimulator.simulizar.monitorrepository.feedthrough/src/org/palladiosimulator/simulizar/monitorrepository/feedthrough/FeedThroughDecorator.java, bundles/org.palladiosimulator.simulizar.monitorrepository.map/src/org/palladiosimulator/simulizar/monitorrepository/map/probeframework/MonitorRepositoryMapProbeFrameworkListenerDecorator.java, bundles/org.palladiosimulator.simulizar.slidingwindow/src/org/palladiosimulator/simulizar/slidingwindow/probeframework/SlidingWindowProbeFrameWorkListenerDecorator.java, bundles/org.palladiosimulator.simulizar.utilization/src/org/palladiosimulator/simulizar/utilization/probeframework/UtilizationProbeFrameworkListenerDecorator.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/AbstractProbeFrameworkListener.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/AbstractRecordingProbeFrameworkListenerDecorator.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/ProbeFrameworkListener.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/runtimestate/SimuComModelFactory.java, tests/org.palladiosimulator.simulizar.slidingwindow.tests/src/org/palladiosimulator/simulizar/slidingwindow/tests/utils/SimuComModelMock.java
Adapts the creation of the probe framework to the new factory interface. 
Should be merged, once https://github.com/PalladioSimulator/Palladio-QuAL-ProbeFramework/pull/6 is merged.
=> [QUAL-41] Adapted to new calculator factory interface

bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/modelobserver/AllocationLookupSyncer.java
Fixes https://jira.palladio-simulator.com/browse/SIMULIZAR-123
=> [Simulizar-123] Fix handling of composite components

bundles/org.palladiosimulator.simulizar.reconfiguration.qvto/src/org/palladiosimulator/simulizar/reconfiguration/qvto/AbstractQVTOExecutor.java
Please check changes and merge
=> enhanced log output for error cases in QVT transformations

README.md, bundles/org.palladiosimulator.simulizar.test.commons/README.md, bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/annotation/SimulationConfigSupplier.java, bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/annotation/SimulationJobSupplier.java, bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/extension/ProvideSimuLizarConfigurationExtension.java, bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/util/RunSimuLizarSimulationJobSupplier.java, bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/util/SimuLizarWorkflowConfigurationProvider.java
Added initial documentation in time for our testing day.
=> Added test documentation

bundles/org.palladiosimulator.simulizar.reconfiguration.qvto/src/org/palladiosimulator/simulizar/reconfiguration/qvto/util/QVToModelCache.java
Changes to fix build with regard to Analyzer-Framework cherry picked from https://github.com/PalladioSimulator/Palladio-Analyzer-SimuLizar/commit/35882240e64992e45aa851b7167b420e96bf2122 (branch Palladio-Analyzer-SimuLizar/simulizar-136)
=> Adapt to upstream changes in Analyzer-Framework

bundles/org.palladiosimulator.simulizar/META-INF/MANIFEST.MF, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/LoadMonitorRepositoryModelIntoBlackboardJob.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/runtimestate/SimuLizarRuntimeState.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/PCMPartitionManager.java, tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/tests/QVToReconfigurationTest.java, tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/tests/SimulizarRunConfigTest.java
Could you please review the changes ?
=> Simulizar 137

bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/EvaluateResultsJob.java
Fixes https://palladio-simulator.atlassian.net/jira/software/c/projects/SIMULIZAR/issues/SIMULIZAR-132.
=> [SIMULIZAR-132] Fix console disappearance

tests/org.palladiosimulator.simulizar.slidingwindow.tests/src/org/palladiosimulator/simulizar/slidingwindow/tests/utils/SimEngineFactoryMock.java
Fixes regression of: https://github.com/PalladioSimulator/Palladio-Simulation-AbstractSimEngine/pull/7
=> Fix compile error due to widened interface in AbstractSimEngine

bundles/org.palladiosimulator.simulizar/.classpath, bundles/org.palladiosimulator.simulizar/.project, bundles/org.palladiosimulator.simulizar/META-INF/MANIFEST.MF, bundles/org.palladiosimulator.simulizar/build.properties, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/di/modules/component/core/SimuLizarRootModule.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/di/modules/scoped/root/CoreRuntimeExtensionBindings.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/ResolveModelPartitionsJob.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/SimuLizarRootJob.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/extensions/DefaultMeasuringPointRepositoryFactory.xtend, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/extensions/DefaultMonitorRepositoryCompletionContributor.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/extensions/DefaultMonitorRepositoryFactory.xtend, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/reconfiguration/Reconfigurator.java
Added automatic default monitor repository creation, if none is specified.
Issue: https://palladio-simulator.atlassian.net/browse/SIMULIZAR-144
=> [SIMULIZAR-144] Default monitor repository

bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/models/AllocationLookupSyncerTestModels.xtend, bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/models/TestModelBase.xtend, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/RDSeffPerformanceSwitch.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/modelobserver/AllocationLookupSyncer.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/runtimestate/FQComponentID.java, tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/modelobserver/tests/AllocationLookupSyncerTest.java, tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/simulation/tests/SubsystemTest.java
Fixes https://palladio-simulator.atlassian.net/browse/SIMULIZAR-145.
=> [SIMULIZAR-145] Support whitebox allocation for subsystems

bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/SimuLizarRootJob.java
Added the SimuCom model validation job, which notifies the user, if there are validation problems in the loaded models.
=> [SIMULIZAR-140] Enable validation after model load

bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/ComposedStructureInnerSwitch.java
The allocation lookup of nested assembly contexts failed before, as it did not take the current assembly context stack into account. As nested assembly contexts can be deployed multiple times by deploying the enclosing component multiple times taking the stack of enclosing assembly contexts into account is crucial. This PR fixes the issue and adds additional error messages for the future.
=> [SIMULIZAR-147] Fix wrong handling of CompositeComponents

releng/org.palladiosimulator.simulizar.targetplatform/tp.target, tests/org.palladiosimulator.simulizar.tests/META-INF/MANIFEST.MF
This PR is part of addressing [PALLADIO-530](https://palladio-simulator.atlassian.net/browse/PALLADIO-530).
Tests most probably only work after  PalladioSimulator/Palladio-Analyzer-SimuCom#30 has been merged.
=> PALLADIO-530 Remove invalid dependency.

bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/util/MeasurementTestUtils.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/UsageScenarioSwitch.java, tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/simulation/tests/EntryLevelSystemCallSimulationTest.java, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/.project, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/default.allocation, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/default.measuringpoint, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/default.monitorrepository, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/default.repository, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/default.resourceenvironment, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/default.slo, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/default.system, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/default.usagemodel, tests/org.palladiosimulator.simulizar.tests/testmodel/entry-level-system-call-return-testmodel/representations.aird
This pull request changes that the simulation saves the output parameter usages on the stack (i.e., the relevant change is https://github.com/PalladioSimulator/Palladio-Analyzer-SimuLizar/blob/6953542664a4ad3c8903d6734bcc6641cc828896/bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/UsageScenarioSwitch.java#L116-L120).
The test tests this by returning a value that is then put into another component that uses the value for delaying the call. The overall response time of the usage scenario is then tested against the value provided by the first provider.
=> FIX SIMULIZAR-135

bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/SimulatedStackHelper.java
As requested by [PALLADIO-503](https://palladio-simulator.atlassian.net/browse/PALLADIO-503), I removed the hand-written StoEx parsers, serialisers and utilities and adjusted the code that used these classes.
This PR requires PalladioSimulator/Palladio-Core-PCM#31 to be merged before it compiles.
=> PALLADIO-503 Remove old StoEx Parser/Serialise/Utilities

bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/ComposedStructureInnerSwitch.java
* potential fix for Simulizar-85
* adding a null check and throwing a new exception in case no parent context exist
=> Simulizar-85

bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/EventDispatcher.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/RepositoryComponentSwitch.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/UsageScenarioSwitch.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/AbstractInterpreterListener.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/AbstractProbeFrameworkListener.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/AssemblyProvidedOperationPassedEvent.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/IInterpreterListener.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/LogDebugListener.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/SystemOperationPassedEvent.java, bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/MonitorRepositoryUtil.java
SystemOperationMeasuringPoints and AssemblyProvidedOperationMeasuringPoints are now identified with all three necessary elements within the ProbeFrameWork.
=> [SIMULIZAR-111] Fix for Assembly- and SystemOperationMeasuringPoints

bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/util/MeasurementTestUtils.java, tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/simulation/tests/AssemblyOperationMeasurementTest.java, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/.project, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/My.resourceenvironment, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/default.allocation, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/default.measuringpoint, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/default.monitorrepository, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/default.repository, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/default.system, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/default.usagemodel, tests/org.palladiosimulator.simulizar.tests/testmodels/simulizar111/representations.aird
This PR adds an additional test for measuring response time for assembly operations. The functionality itself has already been included in the master.
=> Add test for SimuLizar-111
