- org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/MonitorRepositoryUtil.java
EntryLevelSystemCallMeasurementPoints are currently not supported and their usage leads to exceptions.
Jira: [SIMULIZAR-94](https://sdqbuild.ipd.kit.edu/jira/projects/SIMULIZAR/issues/SIMULIZAR-94?)
> Support EntryLevelSystemCallMeasurementPoints

- bundles/org.palladiosimulator.simulizar/plugin.xml
- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/RDSeffSwitch.java
- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/RepositoryComponentSwitch.java
- org.palladiosimulator.simulizar/schema/org.palladiosimulator.simulizar.interpreter.rdseffswitch.exsd
- org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/AbstractRDSeffSwitchFactory.java
- org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/ExplicitDispatchComposedSwitch.java
- org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/IComposableSwitch.java
Enables us to extend the rdseff switch using extension points.
Cherry-picked from: [ExtensibleBehaviourSwitches](https://github.com/PalladioSimulator/Palladio-Analyzer-SimuLizar/tree/ExtensibleBehaviourSwitches)
Jira: [SIMULIZAR-90](https://sdqbuild.ipd.kit.edu/jira/projects/SIMULIZAR/issues/SIMULIZAR-90)
> Cherry-pick extension point for rdseffswitch extension

- releng/org.palladiosimulator.simulizar.targetplatform/tp.target
This PR fixes an issue introduces by changes of PalladioSimulator/Palladio-Simulation-AbstractSimEngine#1. While Simulizar only depends on the abstract simulation engine, the tests need a concrete engine in order to be executable. I added a dependency to the DesmoJ engine, which was the default before the change.
> Added dependency to DesmoJ feature to fix test dependencies.

- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/modelobserver/UsageModelSyncer.java
- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/usagemodel/SimulatedUsageModels.java
Depends on PalladioSimulator/Palladio-Analyzer-SimuCom#2 and synchronizes changes in the think time of closed workloads. I renamed some existing private methods to make sure that it is clear what exactly is propagated.
Again, separate cleanup (bb0c7de) and implementation (0ce4b12)
> Make closed workload reconfigurable

- bundles/org.palladiosimulator.simulizar.aggregation/src/org/palladiosimulizar/aggregation/probeframework/AggregatorsProbeFrameworkListenerDecorator.java
- bundles/org.palladiosimulator.simulizar.monitorrepository.feedthrough/src/org/palladiosimulator/simulizar/monitorrepository/feedthrough/FeedThroughDecorator.java
- bundles/org.palladiosimulator.simulizar.monitorrepository.map/src/org/palladiosimulator/simulizar/monitorrepository/map/probeframework/MonitorRepositoryMapProbeFrameworkListenerDecorator.java
- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/listener/DeferredMeasurementInitialization.java
This pull request adapts the processing of the monitor repository aggregating records to initialize lazily. Since some measurements are only initialized lazily, recorders which depend on the existence of calculators of such measurements may only be initialized after the respective calculator is available.
In order for this PR to be mergeable PalladioSimulator/Palladio-QuAL-ProbeFramework#5 needs to be merged first.
This PR fixes SIMULIZAR-98 (https://jira.palladio-simulator.com/browse/SIMULIZAR-98)
> SIMULIZAR-98 Added capabilities for deferred registration and adapted related listeners

- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/EvaluateResultsJob.java
This modifies the EvaluateResultsJob to enrich the log output with more information making use of 
[this extension for Service Level Objectives](https://github.com/PalladioSimulator/Palladio-Addons-ServiceLevelObjectives/pull/4)
This work is part of a Bachelor 'Fachstudie', which was done at the Reliable Software Systems Group at the University of Stuttgart.
> modified EvaluateResultsJob to call for mapper and evaluate accordingly

- releng/org.palladiosimulator.simulizar.targetplatform/tp.target
The target platform contains a dependency to an Eclipse project that is set to be refreshed. However, we should not do this but depend on fixed version in order to prevent breaking builds without modifications.
> Use fix version for henshin dependency.

- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/utils/ResourceUtil.java
Bug Fixing: If the storing location of the RuntimeMeasurementModel is null (see EXPAUTOM-6).
> Bug Fixing: If the storing location of the RuntimeMeasurementModel is null; addressing EXPAUTOM-6.

- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/InterpreterDefaultContext.java
- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/modelobserver/AllocationLookupSyncer.java
- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/runtimestate/AbstractSimuLizarRuntimeState.java
In the process of implementing linking resource simulation support for SimuLizar [SIMULIZAR-115] a refactoring of the Context class and its way to look up ResourceContainers based on AssemblyContexts became necessary. 
This pull request adapts SimuLizar to the context refactoring in SimuCom Framework and thereby provides the basis for a subsequent PR which will introduce the linking resource simulation support.
> [SIMULIZAR-115] Adapt to context refactoring in SimuComFramework

- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/modelobserver/AllocationLookupSyncer.java
I assumed AllocationContexts only allocation Assemblies. This was wrong. Nevertheless, we only track AssemblyContexts here.
> Fix wrong assumption concerning AllocationContexts

- pom.xml
Tycho 1.7.0 was released. Hence, we can switch back to the release version.
> Switch to release version of Tycho 1.7.0

- releng/org.palladiosimulator.simulizar.targetplatform/tp.target
There are two entries for the thirdparty update site with filter `release`. The one that I removed has been replaced by another entry and is obsolete. However, it breaks release builds and has to be removed.
> Removed obsolete tp entry for release profile.

- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/interpreter/RDSeffSwitch.java
Please review. SimuCom changes must be merged first because I renamed the member variable myContext in ForkedBehaviourProcess to forkContext; this member variable is references in Simulizar in the RDSeffSwitch when creating the InterpreterDefaultContext; thus the Jenkins build of this PR currently fails with a compile error.
> refactoring; use renamed member variable forkContext

- bundles/org.palladiosimulator.simulizar.ui/src/org/palladiosimulator/simulizar/ui/configuration/InterpreterFileNamesInputTab.java
Fix SIMULIZAR-134. Optional SLO model should have an empty default value.
> [SIMULIZAR-134] Fix wrong default

- Jenkinsfile
The branch deployment flag got into the master branch by mistake.
> Deactivate branch deployment

- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/di/modules/scoped/runtime/LinkingResourceSimulationModule.java
When selecting the appropriate network demand calculator, the wrong property was checked. This PR fixes that.
> Fix wrong calculator binding

- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/runconfig/SimuLizarLaunchConfigurationBasedConfigBuilder.java
Corrected type hierarchy of SimuLizarLaunchConfigurationBasedConfigBuilder and added super call to respect base options.
I decided to let it inherit from AbstractSimulationLaunchConfigurationBasedConfigBuilder since it does not make a super call to SimuComLaunchConfigurationBasedConfigBuilder but copies most of the code from there.
Should already work without the changes in the SimuLizar configuration dialog.
> SIMULIZAR-164

- bundles/org.palladiosimulator.simulizar.test.commons/src/org/palladiosimulator/simulizar/test/commons/util/MeasurementTestUtils.java
- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/extensions/DefaultMeasuringPointRepositoryFactory.xtend
- bundles/org.palladiosimulator.simulizar/src/org/palladiosimulator/simulizar/launcher/jobs/extensions/DefaultMonitorRepositoryFactory.xtend
- tests/org.palladiosimulator.simulizar.tests/src/org/palladiosimulator/simulizar/simulation/tests/AcquireReleaseExample.java
This PR fixes [SIMULIZAR-167](https://palladio-simulator.atlassian.net/browse/SIMULIZAR-167). It adds the metrics Holding Time, Waiting Time and State Of Passive Resource to the default set of monitors generated for each passive resource, if no dedicated monitor repository is provided. 
Furthermore, this PR adds the automatic execution of test case [SIMULIZAR-109](https://palladio-simulator.atlassian.net/browse/SIMULIZAR-109) to the set of simulation test cases.
> [SIMULIZAR-167] Generate monitors for passive resources by default

- features/org.palladiosimulator.simulizar.feature/feature.xml
This includes the Simulizar Event Modelling Support in the default PCM bench release.
> Fix for Simulizar-170

- .mvn/extensions.xml
- pom.xml
- releng/org.palladiosimulator.simulizar.targetplatform/tp.target
- Migrate from parent POM version `0.9.0` to the new parent POM version `0.10.0`
- Locally verified build success
- In `pom.xml`:
- Parent POM updated from `0.9.0` to `0.10.0`  
- Renamed property `org.palladiosimulator.maven.tychotprefresh.tplocation.2` to `targetPlatform.relativePath` and trimmed its path value to start at `releng`  
- Removed profile `nightly-snapshot-dependencies` to always use releases instead of snapshots  
- In `.mvn/extensions.xml`:
- Removed `<extension>` block for `org.palladiosimulator:tycho-tp-refresh-maven-plugin`  
- In the target platform `tp.target`:
- Inserted new `<location>` with URI `mvn:org.palladiosimulator:palladio-target-platforms:0.1.0:target:palladio-2023-03`, since the Palladio target platform is now decoupled from the parent POM  
- Unified all …
> Migrate to parent POM version 0.10.0
